[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "mesh2nurbs_rhino3d"
version = "0.2"
dependencies = [
    # "numpy==1.26.4",
    # "scipy",
    # "point_cloud_utils",
    # "pandas",
    # "vedo",
    # "matplotlib",
]

[project.scripts]
mesh2nurbs = "mesh2nurbs_rhino3d.cli_full:main"
fix-mesh = "mesh2nurbs_rhino3d.cli_fix:main"